## AUTHOR : PIERO LOPEZ ROSAS
version: "3.3"
# Servicio para la base de datos MySQL

services:
  db:
    image: mysql:8.0
    container_name: prestashop-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  # Servicio para la aplicación PrestaShop
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop-app
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - prestashop_data:/var/www/html

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: prestashop-phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    env_file:
      - .env

volumes:
  db_data:
  prestashop_data:
