## AUTHOR : PIERO LOPEZ ROSAS

# Servicio para la base de datos MySQL

services:
  db:
    image: mysql:8.0
    container_name: prestashop-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio para la aplicación PrestaShop
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop-app
    depends_on:
       db:
          condition: service_healthy
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - prestashop_data:/var/www/html

  # Servicio para phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: prestashop-phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:80"
    env_file:
      - .env

volumes:
  db_data:
  prestashop_data:
